logging:
  level:
    root: error
    me:
      sonam: info
info:
  app:
    name: Springboot me.sonam.Application
    description: This is a Springboot application
    version: 1.0.0

management:
  endpoint:
    health:
      show-details: always

server:
  port: 8080
trustOrigin: http://localhost:8080

spring:
  application:
    name: email-rest-service
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URL}


permitpath:
  - path: /emails/api/health/*
  - path: /emails
    scopes: message.write


# this is used for getting accesstoken by header filter in jwt-validator (ReactiveRequestContextHolder.class)
auth-server:
  root: http://authorization-server/issuer  #http://localhost:9001
  oauth2token:
    path: /oauth2/token
    params: ?grant_type=client_credentials

token:
  audiences: ${OAUTH_CLIENTS}
  issuerUri: ${ISSUER_URL}
