# This yaml file is for local dev profile
server:
  port: 8085

EUREKA_HOST: localhost:8761
EUREKA_USER: test
EUREKA_PASSWORD: test

eureka:
  client:
    enabled: true

DEFAULT_ZONE: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOST}/eureka

# ISSUER_URL here is used for pulling the public certs from authorization-server for token validation
#ISSUER_URL:  http://10.0.0.28:9001
#ISSUER_URL: http://authorization-server:9001
ISSUER_URL: http://api-gateway:9001/issuer
OAUTH_CLIENTS: oauth-client