logging:
  level:
    root: error
    me:
      sonam: debug
info:
  app:
    name: Springboot me.sonam.Application
    description: This is a Springboot application
    version: 1.0.0

management:
  endpoint:
    health:
      show-details: always

server:
  port: 8080
trustOrigin: http://localhost:8080

spring:
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: https://${EUREKA_USER}:${EUREKA_PASSWORD}@discovery-service.sonam.cloud/eureka

jwt-rest-service-public-key-id: ${JWT_REST_SERVICE}


permitpath:
  - path: /api/health/*